### ISSUE TITLE
Not able to launch the game

### ISSUE THREAD

**Issue by Anth0rx** [Zylann/voxelgame#1]
When I try to run your project in Godot I get the following error message:
```
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
VoxelLibrary not set yet
View distance changed from 8 blocks to 16
ERROR: is_class_enabled: Condition ' !ti ' is true. returned: false
   At: core/class_db.cpp:1283.
wtf class is disabled for: 4
name: TestCube
ERROR: is_class_enabled: Condition ' !ti ' is true. returned: false
   At: core/class_db.cpp:1283.
wtf class is disabled for: 21
name: TestCube
ERROR: is_class_enabled: Condition ' !ti ' is true. returned: false
   At: core/class_db.cpp:1283.
```
I compiled the Godot engine from source with the ```voxel``` and ```opensimplex``` modules.
Do you know how to fix this?

**Comment by Zylann** [comment]
Hmm I have these errors too but they don't prevent me from launching the editor or the game Oo
What is happening exactly? You get a crash? Godot closes?

**Comment by Anth0rx** [comment]
I have the Godot splash screen when starting the project and then nothing happens. It just freezes.

**Comment by Zylann** [comment]
Did you try running it with a debugger attached?

**Comment by Zylann** [comment]
I pushed changes to the demo, is it working now?

**Comment by Anth0rx** [comment]
Now it seems to work. Thank you for you help :)
