### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by nacnud123** [Zylann/voxelgame#60]
This is less of a issue and more of a question but do you have/know the version this screenshot was taken in? I would like to use this kind of world in a project I am making. 

Thanks.

![2016_04_27_2037_half](https://user-images.githubusercontent.com/9938822/54932442-37194a80-4ef1-11e9-9b1b-2c65eed2ab63.png)

**Comment by tinmanjuggernaut** [comment]
The current version of VoxelTools and VoxelGame can support this now. What has been added from the provided code is a translucent blue plane for water, fog, and a grass shader. All of these can be done inside Godot, without needing to work in C++.

**Comment by Zylann** [comment]
This screenshot was taken from the early pure GDScript version of the Voxel module. It can still be reproduced with the C++ module, but it needs a bit of setup to generate water and grass like this.
