### ISSUE TITLE
I really, really need to update this repo

### ISSUE THREAD

**Issue by Zylann** [Zylann/voxelgame#67]
My local version works but is a big mess of testing stuff. Been too busy on the module itself.
Meanwhile you can use tinman's fork: https://github.com/tinmanjuggernaut/voxelgame

**Comment by navett52** [comment]
I am very interested in this repo and can't seem to get this or that fork mentioned to work. I understand being busy, just wanted to show my support! I want to get into voxel terrain generation but am having a hard time finding where to start... though maybe this would be a good place but there's so much going on.

**Comment by tinmanjuggernaut** [comment]
Use my binaries and my fork.
http://tokisan.com/godot-binaries/

**Comment by navett52** [comment]
@tinmanjuggernaut I'll give them a try tomorrow and let you know what happens, thanks!

**Comment by Zylann** [comment]
I just updated the project. Let me know if something doesn't work.
