### ISSUE TITLE
Blocky Game: Vertical railroad stacking

### ISSUE THREAD

**Issue by menip** [Zylann/voxelgame#69]
Currently you can have the following
![image](https://user-images.githubusercontent.com/22862244/89242050-72338f80-d5b5-11ea-9aab-699863d75241.png)
Voxels should probably have a flag `stable` or something that would indicate another voxel can be placed on top of them.

**Comment by Zylann** [comment]
I'm aware of a lot of funny "glitches" like that due to non-implemented stuff. I don't really consider them bugs, as this is still a demo so... 🤷 :D
