### ISSUE TITLE
nonexistent function get_voxel_index_from_name(vname)

### ISSUE THREAD

**Issue by CHIESOFTWARE** [Zylann/voxelgame#70]
OS Ubuntu Studio 20.04
Godot 3.2.2 Prebuild binary rc+cd8d43_x11.64

i just run this scene blocky_game.tscn as main scene and i got this error : 

**nonexistent function get_voxel_index_from_name(vname) in base voxel library**
 
 **blocks.gd / func _create_block(params: Dictionary): / line 199 ->** var id = _voxel_library.get_voxel_index_from_name(vname)

**Comment by Zylann** [comment]
You need to use the latest version of the voxel module, where this function is present https://github.com/Zylann/godot_voxel/blob/66ce79de86d224e95d3362d604ef445f67c10c59/meshers/blocky/voxel_library.cpp#L395

**Comment by CHIESOFTWARE** [comment]
so the Godot 3.2.2 Prebuild binary rc+cd8d43_x11.64 in this case does not work ? .. ok i will include

**Comment by Zylann** [comment]
I don't provide binaries myself, those provided by tinmanjuggernaut must be a bit old compared to master.
