### ISSUE TITLE
blocky_game not working because of debug info

### ISSUE THREAD

**Issue by acs** [Zylann/voxelgame#74]
Hi!

The blocky_game scene fails when it tries to print debug information. The problem [is the code](https://github.com/Zylann/voxelgame/blob/master/project/blocky_game/debug_info.gd#L15).

```
	var stats = _terrain.get_statistics()
	for i in len(stats.stream.remaining_blocks_per_thread):
```

Taking a look to [VoxelTerrain API](https://github.com/Zylann/godot_voxel/blob/master/terrain/voxel_terrain.cpp#L424):

```
Dictionary VoxelTerrain::get_statistics() const {
...
```

the stats info format returned is a dictionary, not the format used in the gdscript.

**Comment by Zylann** [comment]
I think the current demo is currently based on the `godot3.2.3` branch of the module, I did not update it to master yet

**Comment by acs** [comment]
Let me check ... now I can start it, so yes! I don't know how to play yet, so I will recheck it later.

Thanks @Zylann
