### ISSUE TITLE
Blocky_game: terrain does not render with latest stable build in Windows

### ISSUE THREAD

**Issue by brettcoburn** [Zylann/voxelgame#79]
This happens even if you add the missing VoxelViewer to the CharacterAvatar.

When running the game I do see the GUI and the sky, but no terrain. The number of streaming tasks begins to climb rapidly and never stops, unless I press the space bar in which case it drops back to zero.

If it helps, I am able to run test_generator and a small portion of terrain is generated and shown.

I'm using the Windows build that was just recommended here: #77 (comment)

**Comment by Zylann** [comment]
I just pushed a few fixes, does it solve the issue?

**Comment by brettcoburn** [comment]
Fixed, thanks!
