### ISSUE TITLE
Too few arguments for paste call in generator.gd in blocky game

### ISSUE THREAD

**Issue by ValorZard** [Zylann/voxelgame#82]
Its line 166 in generator gd in the blocky game section. its expecting at least four arguments
![image](https://user-images.githubusercontent.com/7539214/115169445-ded2b980-a072-11eb-8c74-14883bf15f2c.png)

**Comment by Zylann** [comment]
This should be fixed now

**Comment by Favkis** [comment]
@Zylann hey I have same problem with latest version

**Comment by Zylann** [comment]
Did you update `voxelgame`? The function call was changed https://github.com/Zylann/voxelgame/blob/aa87dabbf16780c923c59e3dadd078d912e458c8/project/blocky_game/generator/generator.gd#L166

**Comment by Favkis** [comment]
My bad, I used scripts from main addon download, not this one
