### ISSUE TITLE
Not working properly blocky_game.tscn

### ISSUE THREAD

**Issue by HK-SHAO** [Zylann/voxelgame#87]
![image](https://user-images.githubusercontent.com/24982550/148391115-c32f6f33-3761-4185-8491-f4100d01e2e7.png)
![image](https://user-images.githubusercontent.com/24982550/148391290-5860a9f7-8040-45c7-8b93-b7140a0da0c7.png)

When I run blocky_game.tscn, I can't see any squares, but I can see the fired projectiles. Godot keeps reporting errors.

I'm using the Github Actions compiled version:
https://github.com/Zylann/godot_voxel/actions/runs/1568249566

```
E 0:00:01.694   VoxelBufferInternal::copy_from: Condition "other_channel.depth != channel.depth" is true.
  <C++ source>     modules\voxel\storage\voxel_buffer_internal.cpp:557 @ VoxelBufferInternal::copy_from()
```

https://github.com/Zylann/godot_voxel/blob/master/storage/voxel_buffer_internal.cpp

**Comment by Zylann** [comment]
Try the following:
- Delete save files
- Delete this line https://github.com/Zylann/voxelgame/blob/20c70c2fd1e06956bb7a4eb0aea5307c9d5ffad0/project/blocky_game/generator/generator.gd#L77
