### ISSUE TITLE
smooth_terrain/main.tscn does not run properly on Godot 4.0

### ISSUE THREAD

**Issue by jeffb4** [Zylann/voxelgame#94]
Deets:
- Source code `bd2fbfdad10ffe0ae62ae0bb3b1fadfd4098df7d` (HEAD of master branch)
- Godot editor from https://github.com/Zylann/godot_voxel/actions/runs/4896186134 (reads as 
![image](https://github.com/Zylann/voxelgame/assets/3298329/01f48029-f57c-4ee6-a1bb-6ef1eca64d26)
- Godot editor converted this project from Godot 4.1 to 4.0 on initial import. I did this in an editor missing the voxelterrain template
- `blocky_terrain/main.tscn` seems to work as expected

Errors:
The first few times I loaded the scene, the editor threw a warning about an unfound dependency on a test file. This broken dependency doesn't show up at all when I do `Edit dependencies` for the scene.
![image](https://github.com/Zylann/voxelgame/assets/3298329/bd5dab7b-d76a-49aa-9db7-5d58671e6b5a)

More consistently, I'm getting `Attempt to open script 'res://smooth_terrain/rigidbody_spawner.gd' resulted in error 'File not found'.`  I visually confirmed that script was indeed missing.

Running the scene looks like below
![image](https://github.com/Zylann/voxelgame/assets/3298329/51cfc9ab-c8c3-432f-84ae-9fd6dca497dd)

**Comment by Zireael07** [comment]
Most likely the converter renamed rigidbody to either rigidbody2d or rigidbody3d - did you check?

**Comment by jeffb4** [comment]
I did, there's no file starting with the name `rigidbody` in the repository, and I checked the git history for the repo and couldn't find it, either. I know you don't know me so I'm desperate that this doesn't come off wrong, but did it possibly not get added and committed/pushed?

**Comment by jeffb4** [comment]
I was able to set the Generator for `VoxelTerrain` to `VoxelGeneratorNoise2D` and `VoxelGeneratorNoise` and the scene renders. I get errors on the left mouse click voxel spawn effect, something about a missing image: 
![image](https://github.com/Zylann/voxelgame/assets/3298329/eff5eda6-1415-40d3-80c5-5c1f8a2fe624)

**Comment by Zylann** [comment]
`rigidbody_spawner.gd` is a local script I forgot to cleanup, same for the graph...

**Comment by Zylann** [comment]
Try with 0068ffd8e67bbb628dbb95776adfa29544d2c934

**Comment by jeffb4** [comment]
https://github.com/Zylann/voxelgame/commit/0068ffd8e67bbb628dbb95776adfa29544d2c934 worked perfectly - no gripe about Godot version during import, no dependency reference to missing test file, no error about missing script. Thanks!
