### ISSUE TITLE
"Cannot call method 'add_child' on a null value" error

### ISSUE THREAD

**Issue by naphteine** [Zylann/voxelgame#95]
I tried to run Blocky Game using pure Godot 4.1 but it gave me error on VoxelTerrain being undefined. So, I installed Voxel Tools Windows Build (also tried Linux build on Endeavour OS) and tried to run the project but this time it gave me error "Cannot call method 'add_child' on a null value.", on avatar_interaction.gd file line 53, "_terrain.add_child(_cursor)", both on Windows and Linux. I also tried godot4 branch, but it gave me same error message. I am sure I'm doing something wrong but I couldn't figure out on my own. Thank you.

**Comment by Zylann** [comment]
Which scene did you run?

**Comment by naphteine** [comment]
I tried to run blocky_game.tscn, as a main scene in Project Settings and also by pressing F6 and F5, all failing. I added some screenshots, I hope it helps.
![Ekran Görüntüsü - 2023-07-10 21-02-01](https://github.com/Zylann/voxelgame/assets/58526116/c05895d9-3e33-4f92-b612-2c45f9da4415)
![Ekran Görüntüsü - 2023-07-10 21-02-12](https://github.com/Zylann/voxelgame/assets/58526116/f6fae2cf-a389-43b9-b5a3-2fdaa31b5faa)
![Ekran Görüntüsü - 2023-07-10 21-02-33](https://github.com/Zylann/voxelgame/assets/58526116/e101db53-812b-485c-a861-bec4ae41f770)

**Comment by Zylann** [comment]
> I tried to run blocky_game.tscn

That scene is not the one to launch. You should launch `res://blocky_game/main.tscn`.

> as a main scene in Project Settings

The project has no main scene, because it contains more than one main.tscn in several directories.
I should update the `README` because it still indicates the old one.

**Comment by naphteine** [comment]
Ah, all working now. Thank you so much!
